# bonjour.yml
name: Bonjour
on:
  push:
    tags:
      - "*"
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run: docker image build --tag="${IMAGE_NAME}" ./
      # - run: docker container run --volume="$(pwd)":"$(pwd)" --workdir="$(pwd)" "${IMAGE_NAME}" npm run lint
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: "ilyaszk"
          password: "${{ secrets.CI_CD_ESGI }}"
      - name: "Push if on `main`"
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: ./
          tags: "ilyaszk/sayhello:${{ github.ref_name }}"
