# bonjour.yml
name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: hadolint/hadolint-action@v3.1.0
      - run: docker image build --tag="${IMAGE_NAME}" ./
      - run : echo "gfdgfdgdf" > index.js
      - run: docker container run --volume="$(pwd)":"$(pwd)/appo" --workdir="$(pwd)" "${IMAGE_NAME}" npm run lint